name: GitHub-Profile-3D-Contrib-simplify

on:
  schedule: # 00:00 TW (UTC+8) == 16:00 UTC
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib-simplify
    steps:
      - uses: actions/checkout@v3

      - uses: Jung217/github-profile-3d-contrib-simplify@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated" || echo "No changes"
          git push
